mod binomial;
mod chi_squared;
mod exponential;
mod fisher_snedecor;
mod geometric;
mod info;
mod negative_binomial;
mod normal;
mod poisson;
mod uniform;

pub use binomial::Binomial;
pub use chi_squared::ChiSquared;
pub use exponential::Exponential;
pub use fisher_snedecor::FisherSnedecor;
pub use geometric::Geometric;
pub use info::INFO;
pub use negative_binomial::NegativeBinomial;
pub use normal::Normal;
pub use poisson::Poisson;
pub use uniform::Uniform;
