#!/usr/bin/env sh

cargo test || exit 1
cargo build

STATS=./target/debug/stats

title() {
  printf "\033[33m\nshell test: '$1'\033[0m\n"
}

end() {
  printf "\033[33m-----\033[0m\n"
}

stats() {
  title "$@"
  eval $STATS $@
  end
}

stats binom 10 0.2 4

# title "negative binomial (ge)"
# $STATS nbinom 2 0.2 9
